### ISSUE TITLE
error fetching technologies with docker compose up

### ISSUE THREAD

**Issue by aoighost** [Shpota/goxygen#81]
I set up an app using vue and postgres, when loading 8080 with docker compose up, I get the following as it fails to fetch/show the technologies list

app    | 2020/05/07 14:29:17 Error while fetching technologies: server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: db:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp 172.18.0.2:27017: connect: connection refused }, ] }

**Comment by Shpota** [comment]
Hi @aoighost

Thank you for reporting the issue. I will try to solve it as soon as possible.

Could you please provide more information so that I could understand what went wrong.

Please, post the exact command that you used to create the application, your operation system, Docker and docker-compose versions which you can find by running:

```
docker --version
docker-compose --version
```

From the error text, it seems that it tried to start MongoDB instead of PostgreSQL because 27017 is the standard Mongo port. That's why I would also like to check the content of your `docker-compose.yml` and `server/server.go` files.

In the meantime, try creating a repository in the following way and let me know if you have the same issue.

```
go run github.com/shpota/goxygen init --frontend vue --db postgres goxygen-bug
cd goxygen-bug
docker-compose up
```

**Comment by aoighost** [comment]
docker --version
Docker version 19.03.8, build afacb8b
docker-compose --version
docker-compose version 1.25.4, build 8d51620a

oddly, it seems to work with those commands

**Comment by Shpota** [comment]
I am glad it worked for you. Let me know if you have any other issues.

In the meantime, could you please send me the content for the `docker-compose.yml` and `server/server.go` in the project where it doesn't work?
